---
- hosts: all
  gather_facts: False
  become: true
  tasks:
  - name: add backports repository
    apt_repository: repo='deb http://http.debian.net/debian stretch-backports main contrib non-free' state=present update_cache=yes
  - name: Do a "apt-get update"
    apt:
      update_cache: yes
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - name: install packages
    apt: name={{item}} state=present
    with_items:
    - iproute2
    - iptables
    - wrk
    - stress
    - dsniff
    - systemd
    - openjdk-11-jre-headless
#  - template:
#      src: node.service
#      dest: /etc/systemd/system/cockroach.service
#      owner: root
#      group: root
#  - name: Extract cockroach
#    unarchive:
#      src: cockroach-v1.1.5.linux-amd64.tgz 
#      dest: /opt
#  - file:
#      path: /opt/cockroach-v1.1.5.linux-amd64/
#      owner: vagrant
#      group: vagrant
#      recurse: yes
  - file:
      path: /opt/data
      owner: vagrant
      group: vagrant
      state: directory
  - file:
      path: /opt/logs
      owner: vagrant
      group: vagrant
      state: directory
#  - systemd:
#      name: cockroach
#      state: restarted
#      enabled: True
